export const ActivityInformationFormData = {
  pageName: 'Activity Information',
  categories: [
    {
      categoryName: "Merchant's Detail",
      fields: [
        {
          name: 'businessOwnerName',
          label: 'Signatory name as per CNIC',
          type: 'text',
          required: true,
        },
        {
          name: 'ownerOfCNIC',
          label: 'Signatory CNIC',
          type: 'text',
          required: true,
        },

        {
          name: 'fatherSpouseName',
          label: 'Father / Husband / Spouse Name',
          type: 'text',
          required: true,
          desclaimer: '( as per CNIC )',
        },
        {
          name: 'gender',
          label: 'Gender',
          type: 'dropdown',
          required: true,
          options: [
            { label: 'Male', value: 'Male' },
            { label: 'Female', value: 'Female' },
          ],
        },

        {
          name: 'purposeOfAccount',
          label: 'Purpose of Account',
          type: 'dropdown',
          required: true,
          options: [
            { label: 'Retail Payments', value: 'Retail Payments' },
            // DO NOT REMOVE COMMENTED CODE
            // { label: 'Online Payment', value: 'Online Payment' },
            // { label: 'Retail Payments', value: 'Retail Payments' },
            // { label: 'Mini App', value: 'Mini App' },
          ],
        },

        {
          name: 'citizenship',
          label: 'Citizenship',
          type: 'dropdown',
          required: true,
          options: [
            { label: 'Afghanistan', value: 'Afghanistan' },
            { label: 'Albania', value: 'Albania' },
            { label: 'Algeria', value: 'Algeria' },
            { label: 'Andorra', value: 'Andorra' },
            { label: 'Angola', value: 'Angola' },
            { label: 'Antigua', value: 'Antigua' },
            { label: 'Argentina', value: 'Argentina' },
            { label: 'Armenia', value: 'Armenia' },
            { label: 'Australia', value: 'Australia' },
            { label: 'Austria', value: 'Austria' },
            { label: 'Azerbaijan', value: 'Azerbaijan' },
            { label: 'Bahamas', value: 'Bahamas' },
            { label: 'Bahrain', value: 'Bahrain' },
            { label: 'Bangladesh', value: 'Bangladesh' },
            { label: 'Barbados', value: 'Barbados' },
            { label: 'Barbuda', value: 'Barbuda' },
            { label: 'Belarus', value: 'Belarus' },
            { label: 'Belgium', value: 'Belgium' },
            { label: 'Belize', value: 'Belize' },
            { label: 'Benin', value: 'Benin' },
            { label: 'Bhutan', value: 'Bhutan' },
            { label: 'Bolivia', value: 'Bolivia' },
            {
              label: 'Bosnia and Herzegovina',
              value: 'Bosnia and Herzegovina',
            },
            { label: 'Botswana', value: 'Botswana' },
            { label: 'Brazil', value: 'Brazil' },
            { label: 'Brunei', value: 'Brunei' },
            { label: 'Bulgaria', value: 'Bulgaria' },
            { label: 'Burkina Faso', value: 'Burkina Faso' },
            { label: 'Burundi', value: 'Burundi' },
            { label: 'Cambodia', value: 'Cambodia' },
            { label: 'Cameroon', value: 'Cameroon' },
            { label: 'Canada', value: 'Canada' },
            { label: 'Cape Verde', value: 'Cape Verde' },
            {
              label: 'Central African Republic',
              value: 'Central African Republic',
            },
            { label: 'Chad', value: 'Chad' },
            { label: 'Chile', value: 'Chile' },
            { label: 'China', value: 'China' },
            { label: 'Colombia', value: 'Colombia' },
            { label: 'Comoros', value: 'Comoros' },
            { label: 'Cote dlovoire', value: 'Cote dlovoire' },
            { label: 'Costa Rica', value: 'Costa Rica' },
            { label: 'Croatia', value: 'Croatia' },
            { label: 'Cuba', value: 'Cuba' },
            { label: 'Cyprus', value: 'Cyprus' },
            { label: 'Czech Republic', value: 'Czech Republic' },
            { label: 'Czechia', value: 'Czechia' },
            { label: 'Denmark', value: 'Denmark' },
            { label: 'Djibouti', value: 'Djibouti' },
            { label: 'Dominica', value: 'Dominica' },
            { label: 'Dominican Republic', value: 'Dominican Republic' },
            { label: 'Ecuador', value: 'Ecuador' },
            { label: 'Egypt', value: 'Egypt' },
            { label: 'El Salvador', value: 'El Salvador' },
            { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
            { label: 'Eritrea', value: 'Eritrea' },
            { label: 'Estonia', value: 'Estonia' },
            { label: 'Eswatini', value: 'Eswatini' },
            { label: 'Ethiopia', value: 'Ethiopia' },
            { label: 'Fiji', value: 'Fiji' },
            { label: 'Finland', value: 'Finland' },
            { label: 'France', value: 'France' },
            { label: 'Gabon', value: 'Gabon' },
            { label: 'Gambia', value: 'Gambia' },
            { label: 'Georgia', value: 'Georgia' },
            { label: 'Germany', value: 'Germany' },
            { label: 'Ghana', value: 'Ghana' },
            { label: 'Greece', value: 'Greece' },
            { label: 'Grenada', value: 'Grenada' },
            { label: 'Guatemala', value: 'Guatemala' },
            { label: 'Guinea', value: 'Guinea' },
            { label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
            { label: 'Guyana', value: 'Guyana' },
            { label: 'Haiti', value: 'Haiti' },
            { label: 'Honduras', value: 'Honduras' },
            { label: 'Hungary', value: 'Hungary' },
            { label: 'Iceland', value: 'Iceland' },
            { label: 'India', value: 'India' },
            { label: 'Indonesia', value: 'Indonesia' },
            { label: 'Iran', value: 'Iran' },
            { label: 'Iraq', value: 'Iraq' },
            { label: 'Ireland', value: 'Ireland' },
            { label: 'Israel', value: 'Israel' },
            { label: 'Italy', value: 'Italy' },
            { label: 'Jamaica', value: 'Jamaica' },
            { label: 'Japan', value: 'Japan' },
            { label: 'Jordan', value: 'Jordan' },
            { label: 'Kazakhstan', value: 'Kazakhstan' },
            { label: 'Kenya', value: 'Kenya' },
            { label: 'Kiribati', value: 'Kiribati' },
            { label: 'Kuwait', value: 'Kuwait' },
            { label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
            { label: 'Laos', value: 'Laos' },
            { label: 'Latvia', value: 'Latvia' },
            { label: 'Lebanon', value: 'Lebanon' },
            { label: 'Lesotho', value: 'Lesotho' },
            { label: 'Liberia', value: 'Liberia' },
            { label: 'Libya', value: 'Libya' },
            { label: 'Liechtenstein', value: 'Liechtenstein' },
            { label: 'Lithuania', value: 'Lithuania' },
            { label: 'Luxembourg', value: 'Luxembourg' },
            { label: 'Madagascar', value: 'Madagascar' },
            { label: 'Malawi', value: 'Malawi' },
            { label: 'Malaysia', value: 'Malaysia' },
            { label: 'Maldives', value: 'Maldives' },
            { label: 'Mali', value: 'Mali' },
            { label: 'Malta', value: 'Malta' },
            { label: 'Mauritania', value: 'Mauritania' },
            { label: 'Mauritius', value: 'Mauritius' },
            { label: 'Mexico', value: 'Mexico' },
            { label: 'Moldova', value: 'Moldova' },
            { label: 'Monaco', value: 'Monaco' },
            { label: 'Mongolia', value: 'Mongolia' },
            { label: 'Montenegro', value: 'Montenegro' },
            { label: 'Morocco', value: 'Morocco' },
            { label: 'Mozambique', value: 'Mozambique' },
            { label: 'Myanmar', value: 'Myanmar' },
            { label: 'Namibia', value: 'Namibia' },
            { label: 'Nepal', value: 'Nepal' },
            { label: 'Netherlands', value: 'Netherlands' },
            { label: 'New Zealand', value: 'New Zealand' },
            { label: 'Nicaragua', value: 'Nicaragua' },
            { label: 'Niger', value: 'Niger' },
            { label: 'Nigeria', value: 'Nigeria' },
            { label: 'North Korea', value: 'North Korea' },
            { label: 'North Macedonia', value: 'North Macedonia' },
            { label: 'Norway', value: 'Norway' },
            { label: 'Oman', value: 'Oman' },
            { label: 'Palau', value: 'Palau' },
            { label: 'Pakistan', value: 'Pakistan' },
            { label: 'Palestine', value: 'Palestine' },
            { label: 'Panama', value: 'Panama' },
            { label: 'Papua New Guinea', value: 'Papua New Guinea' },
            { label: 'Paraguay', value: 'Paraguay' },
            { label: 'Peru', value: 'Peru' },
            { label: 'Philippines', value: 'Philippines' },
            { label: 'Poland', value: 'Poland' },
            { label: 'Portugal', value: 'Portugal' },
            { label: 'Qatar', value: 'Qatar' },
            { label: 'Romania', value: 'Romania' },
            { label: 'Russia', value: 'Russia' },
            { label: 'Rwanda', value: 'Rwanda' },
            {
              label: 'Saint Kitts and Nevis',
              value: 'Saint Kitts and Nevis',
            },
            { label: 'Saint Lucia', value: 'Saint Lucia' },
            {
              label: 'Saint Vincent and the Grenadines',
              value: 'Saint Vincent and the Grenadines',
            },
            { label: 'Samoa', value: 'Samoa' },
            { label: 'San Marino', value: 'San Marino' },
            { label: 'Saudi Arabia', value: 'Saudi Arabia' },
            { label: 'Senegal', value: 'Senegal' },
            { label: 'Serbia', value: 'Serbia' },
            { label: 'Seychelles', value: 'Seychelles' },
            { label: 'Sierra Leone', value: 'Sierra Leone' },
            { label: 'Singapore', value: 'Singapore' },
            { label: 'Slovakia', value: 'Slovakia' },
            { label: 'Slovenia', value: 'Slovenia' },
            { label: 'Solomon Islands', value: 'Solomon Islands' },
            { label: 'Somalia', value: 'Somalia' },
            { label: 'South Africa', value: 'South Africa' },
            { label: 'South Korea', value: 'South Korea' },
            { label: 'South Sudan', value: 'South Sudan' },
            { label: 'Spain', value: 'Spain' },
            { label: 'Sri Lanka', value: 'Sri Lanka' },
            { label: 'Sudan', value: 'Sudan' },
            { label: 'Suriname', value: 'Suriname' },
            { label: 'Sweden', value: 'Sweden' },
            { label: 'Switzerland', value: 'Switzerland' },
            { label: 'Syria', value: 'Syria' },
            { label: 'Taiwan', value: 'Taiwan' },
            { label: 'Tajikistan', value: 'Tajikistan' },
            { label: 'Tanzania', value: 'Tanzania' },
            { label: 'Thailand', value: 'Thailand' },
            { label: 'Togo', value: 'Togo' },
            { label: 'Tonga', value: 'Tonga' },
            { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
            { label: 'Tunisia', value: 'Tunisia' },
            { label: 'Turkey', value: 'Turkey' },
            { label: 'Turkmenistan', value: 'Turkmenistan' },
            { label: 'Tuvalu', value: 'Tuvalu' },
            { label: 'Uganda', value: 'Uganda' },
            { label: 'Ukraine', value: 'Ukraine' },
            { label: 'United Arab Emirates', value: 'United Arab Emirates' },
            { label: 'United Kingdom', value: 'United Kingdom' },
            { label: 'United States', value: 'United States' },
            { label: 'Uruguay', value: 'Uruguay' },
            { label: 'Uzbekistan', value: 'Uzbekistan' },
            { label: 'Vanuatu', value: 'Vanuatu' },
            { label: 'Vatican City', value: 'Vatican City' },
            { label: 'Venezuela', value: 'Venezuela' },
            { label: 'Vietnam', value: 'Vietnam' },
            { label: 'Yemen', value: 'Yemen' },
            { label: 'Zambia', value: 'Zambia' },
            { label: 'Zimbabwe', value: 'Zimbabwe' },
            { label: 'Kosovo', value: 'Kosovo' },
            { label: 'Marshall Islands', value: 'Marshall Islands' },
            { label: 'Micronesia', value: 'Micronesia' },
            { label: 'Nauru', value: 'Nauru' },
            {
              label: 'Sao Tome and Principe',
              value: 'Sao Tome and Principe',
            },
            { label: 'Timor-Leste', value: 'Timor-Leste' },
            {
              label: 'United States of America',
              value: 'United States of America',
            },
          ],
        },

        {
          name: 'businessName',
          label: 'Business Name',
          type: 'text',
          required: true,
        },
        {
          name: 'legalName',
          label: 'Legal Name',
          type: 'text',
          required: true,
          desclaimer: '( as per Registration Certificate )',
        },
        {
          name: 'ntnNO',
          label: 'NTN No',
          type: 'text',
          required: true,
        },
        {
          name: 'dateOfCorporation',
          label: 'Date of Corporation',
          type: 'date',
          required: true,
        },
        {
          name: 'terrorFinancing',
          label: 'Terror Financing',
          type: 'dropdown',
          required: true,
          options: [
            { label: 'Yes', value: 'Yes' },
            { label: 'No', value: 'No' },
          ],
        },
        {
          name: 'politicallyExposed',
          label: 'Politically Exposed',
          type: 'dropdown',
          required: true,
          options: [
            { label: 'Yes', value: 'Yes' },
            { label: 'No', value: 'No' },
          ],
        },

        {
          name: 'residency',
          label: 'Residency',
          type: 'dropdown',
          required: true,
          options: [
            { label: 'Afghanistan', value: 'Afghanistan' },
            { label: 'Albania', value: 'Albania' },
            { label: 'Algeria', value: 'Algeria' },
            { label: 'Andorra', value: 'Andorra' },
            { label: 'Angola', value: 'Angola' },
            { label: 'Antigua', value: 'Antigua' },
            { label: 'Argentina', value: 'Argentina' },
            { label: 'Armenia', value: 'Armenia' },
            { label: 'Australia', value: 'Australia' },
            { label: 'Austria', value: 'Austria' },
            { label: 'Azerbaijan', value: 'Azerbaijan' },
            { label: 'Bahamas', value: 'Bahamas' },
            { label: 'Bahrain', value: 'Bahrain' },
            { label: 'Bangladesh', value: 'Bangladesh' },
            { label: 'Barbados', value: 'Barbados' },
            { label: 'Barbuda', value: 'Barbuda' },
            { label: 'Belarus', value: 'Belarus' },
            { label: 'Belgium', value: 'Belgium' },
            { label: 'Belize', value: 'Belize' },
            { label: 'Benin', value: 'Benin' },
            { label: 'Bhutan', value: 'Bhutan' },
            { label: 'Bolivia', value: 'Bolivia' },
            {
              label: 'Bosnia and Herzegovina',
              value: 'Bosnia and Herzegovina',
            },
            { label: 'Botswana', value: 'Botswana' },
            { label: 'Brazil', value: 'Brazil' },
            { label: 'Brunei', value: 'Brunei' },
            { label: 'Bulgaria', value: 'Bulgaria' },
            { label: 'Burkina Faso', value: 'Burkina Faso' },
            { label: 'Burundi', value: 'Burundi' },
            { label: 'Cambodia', value: 'Cambodia' },
            { label: 'Cameroon', value: 'Cameroon' },
            { label: 'Canada', value: 'Canada' },
            { label: 'Cape Verde', value: 'Cape Verde' },
            {
              label: 'Central African Republic',
              value: 'Central African Republic',
            },
            { label: 'Chad', value: 'Chad' },
            { label: 'Chile', value: 'Chile' },
            { label: 'China', value: 'China' },
            { label: 'Colombia', value: 'Colombia' },
            { label: 'Comoros', value: 'Comoros' },
            { label: 'Cote dlovoire', value: 'Cote dlovoire' },
            { label: 'Costa Rica', value: 'Costa Rica' },
            { label: 'Croatia', value: 'Croatia' },
            { label: 'Cuba', value: 'Cuba' },
            { label: 'Cyprus', value: 'Cyprus' },
            { label: 'Czech Republic', value: 'Czech Republic' },
            { label: 'Czechia', value: 'Czechia' },
            { label: 'Denmark', value: 'Denmark' },
            { label: 'Djibouti', value: 'Djibouti' },
            { label: 'Dominica', value: 'Dominica' },
            { label: 'Dominican Republic', value: 'Dominican Republic' },
            { label: 'Ecuador', value: 'Ecuador' },
            { label: 'Egypt', value: 'Egypt' },
            { label: 'El Salvador', value: 'El Salvador' },
            { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
            { label: 'Eritrea', value: 'Eritrea' },
            { label: 'Estonia', value: 'Estonia' },
            { label: 'Eswatini', value: 'Eswatini' },
            { label: 'Ethiopia', value: 'Ethiopia' },
            { label: 'Fiji', value: 'Fiji' },
            { label: 'Finland', value: 'Finland' },
            { label: 'France', value: 'France' },
            { label: 'Gabon', value: 'Gabon' },
            { label: 'Gambia', value: 'Gambia' },
            { label: 'Georgia', value: 'Georgia' },
            { label: 'Germany', value: 'Germany' },
            { label: 'Ghana', value: 'Ghana' },
            { label: 'Greece', value: 'Greece' },
            { label: 'Grenada', value: 'Grenada' },
            { label: 'Guatemala', value: 'Guatemala' },
            { label: 'Guinea', value: 'Guinea' },
            { label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
            { label: 'Guyana', value: 'Guyana' },
            { label: 'Haiti', value: 'Haiti' },
            { label: 'Honduras', value: 'Honduras' },
            { label: 'Hungary', value: 'Hungary' },
            { label: 'Iceland', value: 'Iceland' },
            { label: 'India', value: 'India' },
            { label: 'Indonesia', value: 'Indonesia' },
            { label: 'Iran', value: 'Iran' },
            { label: 'Iraq', value: 'Iraq' },
            { label: 'Ireland', value: 'Ireland' },
            { label: 'Israel', value: 'Israel' },
            { label: 'Italy', value: 'Italy' },
            { label: 'Jamaica', value: 'Jamaica' },
            { label: 'Japan', value: 'Japan' },
            { label: 'Jordan', value: 'Jordan' },
            { label: 'Kazakhstan', value: 'Kazakhstan' },
            { label: 'Kenya', value: 'Kenya' },
            { label: 'Kiribati', value: 'Kiribati' },
            { label: 'Kuwait', value: 'Kuwait' },
            { label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
            { label: 'Laos', value: 'Laos' },
            { label: 'Latvia', value: 'Latvia' },
            { label: 'Lebanon', value: 'Lebanon' },
            { label: 'Lesotho', value: 'Lesotho' },
            { label: 'Liberia', value: 'Liberia' },
            { label: 'Libya', value: 'Libya' },
            { label: 'Liechtenstein', value: 'Liechtenstein' },
            { label: 'Lithuania', value: 'Lithuania' },
            { label: 'Luxembourg', value: 'Luxembourg' },
            { label: 'Madagascar', value: 'Madagascar' },
            { label: 'Malawi', value: 'Malawi' },
            { label: 'Malaysia', value: 'Malaysia' },
            { label: 'Maldives', value: 'Maldives' },
            { label: 'Mali', value: 'Mali' },
            { label: 'Malta', value: 'Malta' },
            { label: 'Mauritania', value: 'Mauritania' },
            { label: 'Mauritius', value: 'Mauritius' },
            { label: 'Mexico', value: 'Mexico' },
            { label: 'Moldova', value: 'Moldova' },
            { label: 'Monaco', value: 'Monaco' },
            { label: 'Mongolia', value: 'Mongolia' },
            { label: 'Montenegro', value: 'Montenegro' },
            { label: 'Morocco', value: 'Morocco' },
            { label: 'Mozambique', value: 'Mozambique' },
            { label: 'Myanmar', value: 'Myanmar' },
            { label: 'Namibia', value: 'Namibia' },
            { label: 'Nepal', value: 'Nepal' },
            { label: 'Netherlands', value: 'Netherlands' },
            { label: 'New Zealand', value: 'New Zealand' },
            { label: 'Nicaragua', value: 'Nicaragua' },
            { label: 'Niger', value: 'Niger' },
            { label: 'Nigeria', value: 'Nigeria' },
            { label: 'North Korea', value: 'North Korea' },
            { label: 'North Macedonia', value: 'North Macedonia' },
            { label: 'Norway', value: 'Norway' },
            { label: 'Oman', value: 'Oman' },
            { label: 'Palau', value: 'Palau' },
            { label: 'Pakistan', value: 'Pakistan' },
            { label: 'Palestine', value: 'Palestine' },
            { label: 'Panama', value: 'Panama' },
            { label: 'Papua New Guinea', value: 'Papua New Guinea' },
            { label: 'Paraguay', value: 'Paraguay' },
            { label: 'Peru', value: 'Peru' },
            { label: 'Philippines', value: 'Philippines' },
            { label: 'Poland', value: 'Poland' },
            { label: 'Portugal', value: 'Portugal' },
            { label: 'Qatar', value: 'Qatar' },
            { label: 'Romania', value: 'Romania' },
            { label: 'Russia', value: 'Russia' },
            { label: 'Rwanda', value: 'Rwanda' },
            {
              label: 'Saint Kitts and Nevis',
              value: 'Saint Kitts and Nevis',
            },
            { label: 'Saint Lucia', value: 'Saint Lucia' },
            {
              label: 'Saint Vincent and the Grenadines',
              value: 'Saint Vincent and the Grenadines',
            },
            { label: 'Samoa', value: 'Samoa' },
            { label: 'San Marino', value: 'San Marino' },
            { label: 'Saudi Arabia', value: 'Saudi Arabia' },
            { label: 'Senegal', value: 'Senegal' },
            { label: 'Serbia', value: 'Serbia' },
            { label: 'Seychelles', value: 'Seychelles' },
            { label: 'Sierra Leone', value: 'Sierra Leone' },
            { label: 'Singapore', value: 'Singapore' },
            { label: 'Slovakia', value: 'Slovakia' },
            { label: 'Slovenia', value: 'Slovenia' },
            { label: 'Solomon Islands', value: 'Solomon Islands' },
            { label: 'Somalia', value: 'Somalia' },
            { label: 'South Africa', value: 'South Africa' },
            { label: 'South Korea', value: 'South Korea' },
            { label: 'South Sudan', value: 'South Sudan' },
            { label: 'Spain', value: 'Spain' },
            { label: 'Sri Lanka', value: 'Sri Lanka' },
            { label: 'Sudan', value: 'Sudan' },
            { label: 'Suriname', value: 'Suriname' },
            { label: 'Sweden', value: 'Sweden' },
            { label: 'Switzerland', value: 'Switzerland' },
            { label: 'Syria', value: 'Syria' },
            { label: 'Taiwan', value: 'Taiwan' },
            { label: 'Tajikistan', value: 'Tajikistan' },
            { label: 'Tanzania', value: 'Tanzania' },
            { label: 'Thailand', value: 'Thailand' },
            { label: 'Togo', value: 'Togo' },
            { label: 'Tonga', value: 'Tonga' },
            { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
            { label: 'Tunisia', value: 'Tunisia' },
            { label: 'Turkey', value: 'Turkey' },
            { label: 'Turkmenistan', value: 'Turkmenistan' },
            { label: 'Tuvalu', value: 'Tuvalu' },
            { label: 'Uganda', value: 'Uganda' },
            { label: 'Ukraine', value: 'Ukraine' },
            { label: 'United Arab Emirates', value: 'United Arab Emirates' },
            { label: 'United Kingdom', value: 'United Kingdom' },
            { label: 'United States', value: 'United States' },
            { label: 'Uruguay', value: 'Uruguay' },
            { label: 'Uzbekistan', value: 'Uzbekistan' },
            { label: 'Vanuatu', value: 'Vanuatu' },
            { label: 'Vatican City', value: 'Vatican City' },
            { label: 'Venezuela', value: 'Venezuela' },
            { label: 'Vietnam', value: 'Vietnam' },
            { label: 'Yemen', value: 'Yemen' },
            { label: 'Zambia', value: 'Zambia' },
            { label: 'Zimbabwe', value: 'Zimbabwe' },
            { label: 'Kosovo', value: 'Kosovo' },
            { label: 'Marshall Islands', value: 'Marshall Islands' },
            { label: 'Micronesia', value: 'Micronesia' },
            { label: 'Nauru', value: 'Nauru' },
            {
              label: 'Sao Tome and Principe',
              value: 'Sao Tome and Principe',
            },
            { label: 'Timor-Leste', value: 'Timor-Leste' },
            {
              label: 'United States of America',
              value: 'United States of America',
            },
          ],
        },
      ],
    },

    {
      categoryName: 'Contact Details',
      fields: [
        {
          name: 'email',
          label: 'Email Address',
          type: 'disabledInput',
          required: true,
        },
        {
          name: 'city',
          label: 'City',
          type: 'dropdown',
          required: true,
          options: [
            { label: 'Abbaspur', value: 'Abbaspur' },
            { label: 'Abbottabad', value: 'Abbottabad' },
            { label: 'Adezai', value: 'Adezai' },
            { label: 'Ahmadpur East', value: 'Ahmadpur East' },
            { label: 'Ahmed Nager Chatha', value: 'Ahmed Nager Chatha' },
            { label: 'Ahmedpur Sial', value: 'Ahmedpur Sial' },
            { label: 'Akora Khattak', value: 'Akora Khattak' },
            { label: 'Alai', value: 'Alai' },
            { label: 'Al Abad', value: 'Al Abad' },
            { label: 'Ali Khan Abad', value: 'Ali Khan Abad' },
            { label: 'Alipur', value: 'Alipur' },
            { label: 'Alizai', value: 'Alizai' },
            { label: 'Alpuri', value: 'Alpuri' },
            { label: 'AliWala', value: 'AliWala' },
            { label: 'Astore', value: 'Astore' },
            { label: 'Athmuqam', value: 'Athmuqam' },
            { label: 'Attock', value: 'Attock' },
            { label: 'Awaran', value: 'Awaran' },
            { label: 'Ayubia', value: 'Ayubia' },
            { label: 'Batala Kot', value: 'Batala Kot' },
            { label: 'Badin', value: 'Badin' },
            { label: 'Bagh', value: 'Bagh' },
            { label: 'Bahawalnagar', value: 'Bahawalnagar' },
            { label: 'Bahawalpur', value: 'Bahawalpur' },
            { label: 'Bajaur Agency', value: 'Bajaur Agency' },
            { label: 'Bakarki', value: 'Bakarki' },
            { label: 'Bala Kot', value: 'Bala Kot' },
            { label: 'Balambat Lal Qilla', value: 'Balambat Lal Qilla' },
            { label: 'Baloch', value: 'Baloch' },
            { label: 'Banda Daud Shah', value: 'Banda Daud Shah' },
            { label: 'Bannu', value: 'Bannu' },
            { label: 'Barawal', value: 'Barawal' },
            { label: 'Barkhan', value: 'Barkhan' },
            { label: 'Barmala', value: 'Barmala' },
            { label: 'Batkhela', value: 'Batkhela' },
            { label: 'Battagram', value: 'Battagram' },
            { label: 'Bela', value: 'Bela' },
            { label: 'Besima', value: 'Besima' },
            { label: 'Bhag', value: 'Bhag' },
            { label: 'Bhalwal', value: 'Bhalwal' },
            { label: 'Bhakkar', value: 'Bhakkar' },
            { label: 'Bhalwal', value: 'Bhalwal' },
            { label: 'Bhawana', value: 'Bhawana' },
            { label: 'Bhera', value: 'Bhera' },
            { label: 'Bhimber', value: 'Bhimber' },
            { label: 'Bhiria Road', value: 'Bhiria Road' },
            { label: 'Bhirkan', value: 'Bhirkan' },
            { label: 'Bilrote', value: 'Bilrote' },
            { label: 'Bisham', value: 'Bisham' },
            { label: 'Bolan (Dhadar)', value: 'Bolan (Dhadar)' },
            { label: 'Bunir', value: 'Bunir' },
            { label: 'Buurewala', value: 'Buurewala' },
            { label: 'Chachro', value: 'Chachro' },
            { label: 'Chaghi', value: 'Chaghi' },
            { label: 'Chak Jhumra', value: 'Chak Jhumra' },
            { label: 'Chakdara', value: 'Chakdara' },
            { label: 'Chakesar', value: 'Chakesar' },
            { label: 'Chakwal', value: 'Chakwal' },
            { label: 'Chaman', value: 'Chaman' },
            { label: 'Chamber', value: 'Chamber' },
            { label: 'Charcoal', value: 'Charcoal' },
            { label: 'Charsadda', value: 'Charsadda' },
            { label: 'Chitral', value: 'Chitral' },
            { label: 'Chowk Azam', value: 'Chowk Azam' },
            { label: 'Cherat', value: 'Cherat' },
            { label: 'Chitkan', value: 'Chitkan' },
            { label: 'Chilas', value: 'Chilas' },
            { label: 'Chiniot', value: 'Chiniot' },
            { label: 'Chistian', value: 'Chistian' },
            { label: 'Chowk Munda', value: 'Chowk Munda' },
            { label: 'Chowk Sarwar Shaheed', value: 'Chowk Sarwar Shaheed' },
            { label: 'Dadu', value: 'Dadu' },
            { label: 'Dagar', value: 'Dagar' },
            { label: 'Dadu', value: 'Dadu' },
            { label: 'Dabir', value: 'Dabir' },
            { label: 'Dadu', value: 'Dadu' },
            { label: 'Danyore', value: 'Danyore' },
            { label: 'Darra Adam Khel', value: 'Darra Adam Khel' },
            { label: 'Darya Khan', value: 'Darya Khan' },
            { label: 'Daska', value: 'Daska' },
            { label: 'Datta', value: 'Datta' },
            { label: 'Dadu', value: 'Dadu' },
            { label: 'Daska', value: 'Daska' },
            { label: 'Dolatpur', value: 'Dolatpur' },
            { label: 'Domer', value: 'Domer' },
            { label: 'Drish', value: 'Drish' },
            { label: 'Dubairy(AK)', value: 'Dubairy(AK)' },
            { label: 'Duki', value: 'Duki' },
            { label: 'Dunyapur', value: 'Dunyapur' },
            { label: 'Dureji', value: 'Dureji' },
            { label: 'Faisalabad', value: 'Faisalabad' },
            { label: 'Fateh Jang', value: 'Fateh Jang' },
            { label: 'Fateh Garh', value: 'Fateh Garh' },
            { label: 'Fazilpur', value: 'Fazilpur' },
            { label: 'Feroza Wala', value: 'Feroza Wala' },
            { label: 'Fort Abbas', value: 'Fort Abbas' },
            { label: 'Forward Kanula', value: 'Forward Kanula' },
            { label: 'Gadani', value: 'Gadani' },
            { label: 'Gambat', value: 'Gambat' },
            { label: 'Garhiyasin', value: 'Garhiyasin' },
            { label: 'Gari Habibullah', value: 'Gari Habibullah' },
            { label: 'Ghotki', value: 'Ghotki' },
            { label: 'Gilgit', value: 'Gilgit' },
            { label: 'Gojra', value: 'Gojra' },
            { label: 'Gujar Khan', value: 'Gujar Khan' },
            { label: 'Gujranwala', value: 'Gujranwala' },
            { label: 'Gujrat', value: 'Gujrat' },
            { label: 'Gwadar', value: 'Gwadar' },
            { label: 'Gwash', value: 'Gwash' },
            { label: 'Hafizabad', value: 'Hafizabad' },
            { label: 'Hangu', value: 'Hangu' },
            { label: 'Haripur', value: 'Haripur' },
            { label: 'Harnai', value: 'Harnai' },
            { label: 'Hasilpur', value: 'Hasilpur' },
            { label: 'Haveli Kahuta', value: 'Haveli Kahuta' },
            { label: 'Havelian', value: 'Havelian' },
            { label: 'Hassan Abdal', value: 'Hassan Abdal' },
            { label: 'Hasil', value: 'Hasil' },
            { label: 'Jamshoro', value: 'Jamshoro' },
            { label: 'Jand', value: 'Jand' },
            { label: 'Jamshedka', value: 'Jamshedka' },
            { label: 'Jati', value: 'Jati' },
            { label: 'Jatli', value: 'Jatli' },
            { label: 'Jauharabad', value: 'Jauharabad' },
            { label: 'Jhal Magsi', value: 'Jhal Magsi' },
            { label: 'Jhatpat', value: 'Jhatpat' },
            { label: 'Jhando Mari', value: 'Jhando Mari' },
            { label: 'Jhang', value: 'Jhang' },
            { label: 'Jhelum', value: 'Jhelum' },
            { label: 'Jhel Pat', value: 'Jhel Pat' },
            { label: 'Jiwani', value: 'Jiwani' },
            { label: 'Johi', value: 'Johi' },
            { label: 'Jampur', value: 'Jampur' },
            { label: 'Kot Waza', value: 'Kot Waza' },
            { label: 'Kachhi', value: 'Kachhi' },
            { label: 'Haveli Lakha', value: 'Haveli Lakha' },
            { label: 'Hub', value: 'Hub' },
            { label: 'Hunza Nagar', value: 'Hunza Nagar' },
            { label: 'Hurnai', value: 'Hurnai' },
            { label: 'Hussain Bux Mari', value: 'Hussain Bux Mari' },
            { label: 'Hyderabad', value: 'Hyderabad' },
            { label: 'Ishkoman', value: 'Ishkoman' },
            { label: 'Islamabad', value: 'Islamabad' },
            { label: 'Islamkot', value: 'Islamkot' },
            { label: 'Jacobabad', value: 'Jacobabad' },
            { label: 'Jaffarabad', value: 'Jaffarabad' },
            { label: 'Jahaniyan', value: 'Jahaniyan' },
            { label: 'Jalalpur', value: 'Jalalpur' },
            { label: 'Jalalpur Jattan', value: 'Jalalpur Jattan' },
            { label: 'Jami Nawaz Ali', value: 'Jami Nawaz Ali' },
            { label: 'Jamrud', value: 'Jamrud' },
            { label: 'Jamshoro', value: 'Jamshoro' },
            { label: 'Kachhi', value: 'Kachhi' },
            { label: 'Kahan', value: 'Kahan' },
            { label: 'Kahror Pakka', value: 'Kahror Pakka' },
            { label: 'Kahuta', value: 'Kahuta' },
            { label: 'Kala Dhaka', value: 'Kala Dhaka' },
            { label: 'Kalabagh', value: 'Kalabagh' },
            { label: 'Kalat', value: 'Kalat' },
            { label: 'Kallar Kahar', value: 'Kallar Kahar' },
            { label: 'Kallar Sayyedan', value: 'Kallar Sayyedan' },
            { label: 'Kalur Kot', value: 'Kalur Kot' },
            { label: 'Kamalia', value: 'Kamalia' },
            { label: 'Kambar Ali Khan', value: 'Kambar Ali Khan' },
            { label: 'Kamoke', value: 'Kamoke' },
            { label: 'Kandhkot', value: 'Kandhkot' },
            { label: 'Kandia', value: 'Kandia' },
            { label: 'Kandaro', value: 'Kandaro' },
            { label: 'Kanraj', value: 'Kanraj' },
            { label: 'Karachi', value: 'Karachi' },
          ],
        },
        {
          name: 'businessAddress',
          label: 'Business Address',
          type: 'text',
          required: true,
        },
        {
          name: 'correspondenceAddress',
          label:
            'Click here if correspondence address is same as business address',
          type: 'checkItem',
          required: true,
        },
        {
          name: 'correspondenceAddress',
          label: 'Correspondence Address',
          type: 'text',
          required: true,
        },
        {
          name: 'accountHandlerIsdifferentfromOwnerAccountHolder',
          label: 'Account Handler is different from Owner/Account Holder',
          type: 'dropdown',
          required: true,
          options: [
            { label: 'Yes', value: 'Yes' },
            { label: 'No', value: 'No' },
          ],
        },
        {
          name: 'primaryPhoneNo',
          label: 'Primary Phone No',
          type: 'disabledInput',
          required: true,
        },
        {
          name: 'secondaryPhoneNo',
          label: 'Secondary Phone No',
          type: 'text',
          required: false,
        },
      ],
    },
  ],
};
