// Do NOt Remove Commented Fields

export const storeDetailsFormData = {
  pageName: 'Store Details',
  categories: [
    {
      categoryName: '',
      fields: [
        {
          label: 'Store Type',
          name: 'storeType',
          type: 'checkBoxInputMulti',
          options: [
            // { value: 'Online', label: 'Online' },
            { value: 'Retail', label: 'Retail' },
          ],
          required: true,
        },
        // {
        //   label: 'Web Store Name *',
        //   name: 'webstoreName',
        //   type: 'text',
        //   show: ['Online'],
        // },
        {
          label: 'Store Name',
          name: 'storeName',
          type: 'text',
          show: ['Online', 'Retail'],
          required: true,
        },
        // {
        //   label: 'Website URL *',
        //   name: 'webstoreURL',
        //   type: 'text',
        //   show: ['Online'],
        // },

        {
          label: 'Street Address',
          name: 'streetAddress',
          type: 'text',
          show: ['Online', 'Retail'],
          required: true,
        },
        {
          label: 'City',
          name: 'city',
          type: 'dropDown',
          show: ['Online', 'Retail'],
          required: true,
          options: [
            { label: 'Abbaspur', value: 'Abbaspur' },
            { label: 'Abbottabad', value: 'Abbottabad' },
            { label: 'Adezai', value: 'Adezai' },
            { label: 'Ahmadpur East', value: 'Ahmadpur East' },
            { label: 'Ahmed Nager Chatha', value: 'Ahmed Nager Chatha' },
            { label: 'Ahmedpur Sial', value: 'Ahmedpur Sial' },
            { label: 'Akora Khattak', value: 'Akora Khattak' },
            { label: 'Alai', value: 'Alai' },
            { label: 'Al Abad', value: 'Al Abad' },
            { label: 'Ali Khan Abad', value: 'Ali Khan Abad' },
            { label: 'Alipur', value: 'Alipur' },
            { label: 'Alizai', value: 'Alizai' },
            { label: 'Alpuri', value: 'Alpuri' },
            { label: 'AliWala', value: 'AliWala' },
            { label: 'Astore', value: 'Astore' },
            { label: 'Athmuqam', value: 'Athmuqam' },
            { label: 'Attock', value: 'Attock' },
            { label: 'Awaran', value: 'Awaran' },
            { label: 'Ayubia', value: 'Ayubia' },
            { label: 'Batala Kot', value: 'Batala Kot' },
            { label: 'Badin', value: 'Badin' },
            { label: 'Bagh', value: 'Bagh' },
            { label: 'Bahawalnagar', value: 'Bahawalnagar' },
            { label: 'Bahawalpur', value: 'Bahawalpur' },
            { label: 'Bajaur Agency', value: 'Bajaur Agency' },
            { label: 'Bakarki', value: 'Bakarki' },
            { label: 'Bala Kot', value: 'Bala Kot' },
            { label: 'Balambat Lal Qilla', value: 'Balambat Lal Qilla' },
            { label: 'Baloch', value: 'Baloch' },
            { label: 'Banda Daud Shah', value: 'Banda Daud Shah' },
            { label: 'Bannu', value: 'Bannu' },
            { label: 'Barawal', value: 'Barawal' },
            { label: 'Barkhan', value: 'Barkhan' },
            { label: 'Barmala', value: 'Barmala' },
            { label: 'Batkhela', value: 'Batkhela' },
            { label: 'Battagram', value: 'Battagram' },
            { label: 'Bela', value: 'Bela' },
            { label: 'Besima', value: 'Besima' },
            { label: 'Bhag', value: 'Bhag' },
            { label: 'Bhalwal', value: 'Bhalwal' },
            { label: 'Bhakkar', value: 'Bhakkar' },
            { label: 'Bhalwal', value: 'Bhalwal' },
            { label: 'Bhawana', value: 'Bhawana' },
            { label: 'Bhera', value: 'Bhera' },
            { label: 'Bhimber', value: 'Bhimber' },
            { label: 'Bhiria Road', value: 'Bhiria Road' },
            { label: 'Bhirkan', value: 'Bhirkan' },
            { label: 'Bilrote', value: 'Bilrote' },
            { label: 'Bisham', value: 'Bisham' },
            { label: 'Bolan (Dhadar)', value: 'Bolan (Dhadar)' },
            { label: 'Bunir', value: 'Bunir' },
            { label: 'Buurewala', value: 'Buurewala' },
            { label: 'Chachro', value: 'Chachro' },
            { label: 'Chaghi', value: 'Chaghi' },
            { label: 'Chak Jhumra', value: 'Chak Jhumra' },
            { label: 'Chakdara', value: 'Chakdara' },
            { label: 'Chakesar', value: 'Chakesar' },
            { label: 'Chakwal', value: 'Chakwal' },
            { label: 'Chaman', value: 'Chaman' },
            { label: 'Chamber', value: 'Chamber' },
            { label: 'Charcoal', value: 'Charcoal' },
            { label: 'Charsadda', value: 'Charsadda' },
            { label: 'Chitral', value: 'Chitral' },
            { label: 'Chowk Azam', value: 'Chowk Azam' },
            { label: 'Cherat', value: 'Cherat' },
            { label: 'Chitkan', value: 'Chitkan' },
            { label: 'Chilas', value: 'Chilas' },
            { label: 'Chiniot', value: 'Chiniot' },
            { label: 'Chistian', value: 'Chistian' },
            { label: 'Chowk Munda', value: 'Chowk Munda' },
            { label: 'Chowk Sarwar Shaheed', value: 'Chowk Sarwar Shaheed' },
            { label: 'Dadu', value: 'Dadu' },
            { label: 'Dagar', value: 'Dagar' },
            { label: 'Dadu', value: 'Dadu' },
            { label: 'Dabir', value: 'Dabir' },
            { label: 'Dadu', value: 'Dadu' },
            { label: 'Danyore', value: 'Danyore' },
            { label: 'Darra Adam Khel', value: 'Darra Adam Khel' },
            { label: 'Darya Khan', value: 'Darya Khan' },
            { label: 'Daska', value: 'Daska' },
            { label: 'Datta', value: 'Datta' },
            { label: 'Dadu', value: 'Dadu' },
            { label: 'Daska', value: 'Daska' },
            { label: 'Dolatpur', value: 'Dolatpur' },
            { label: 'Domer', value: 'Domer' },
            { label: 'Drish', value: 'Drish' },
            { label: 'Dubairy(AK)', value: 'Dubairy(AK)' },
            { label: 'Duki', value: 'Duki' },
            { label: 'Dunyapur', value: 'Dunyapur' },
            { label: 'Dureji', value: 'Dureji' },
            { label: 'Faisalabad', value: 'Faisalabad' },
            { label: 'Fateh Jang', value: 'Fateh Jang' },
            { label: 'Fateh Garh', value: 'Fateh Garh' },
            { label: 'Fazilpur', value: 'Fazilpur' },
            { label: 'Feroza Wala', value: 'Feroza Wala' },
            { label: 'Fort Abbas', value: 'Fort Abbas' },
            { label: 'Forward Kanula', value: 'Forward Kanula' },
            { label: 'Gadani', value: 'Gadani' },
            { label: 'Gambat', value: 'Gambat' },
            { label: 'Garhiyasin', value: 'Garhiyasin' },
            { label: 'Gari Habibullah', value: 'Gari Habibullah' },
            { label: 'Ghotki', value: 'Ghotki' },
            { label: 'Gilgit', value: 'Gilgit' },
            { label: 'Gojra', value: 'Gojra' },
            { label: 'Gujar Khan', value: 'Gujar Khan' },
            { label: 'Gujranwala', value: 'Gujranwala' },
            { label: 'Gujrat', value: 'Gujrat' },
            { label: 'Gwadar', value: 'Gwadar' },
            { label: 'Gwash', value: 'Gwash' },
            { label: 'Hafizabad', value: 'Hafizabad' },
            { label: 'Hangu', value: 'Hangu' },
            { label: 'Haripur', value: 'Haripur' },
            { label: 'Harnai', value: 'Harnai' },
            { label: 'Hasilpur', value: 'Hasilpur' },
            { label: 'Haveli Kahuta', value: 'Haveli Kahuta' },
            { label: 'Havelian', value: 'Havelian' },
            { label: 'Hassan Abdal', value: 'Hassan Abdal' },
            { label: 'Hasil', value: 'Hasil' },
            { label: 'Jamshoro', value: 'Jamshoro' },
            { label: 'Jand', value: 'Jand' },
            { label: 'Jamshedka', value: 'Jamshedka' },
            { label: 'Jati', value: 'Jati' },
            { label: 'Jatli', value: 'Jatli' },
            { label: 'Jauharabad', value: 'Jauharabad' },
            { label: 'Jhal Magsi', value: 'Jhal Magsi' },
            { label: 'Jhatpat', value: 'Jhatpat' },
            { label: 'Jhando Mari', value: 'Jhando Mari' },
            { label: 'Jhang', value: 'Jhang' },
            { label: 'Jhelum', value: 'Jhelum' },
            { label: 'Jhel Pat', value: 'Jhel Pat' },
            { label: 'Jiwani', value: 'Jiwani' },
            { label: 'Johi', value: 'Johi' },
            { label: 'Jampur', value: 'Jampur' },
            { label: 'Kot Waza', value: 'Kot Waza' },
            { label: 'Kachhi', value: 'Kachhi' },
            { label: 'Haveli Lakha', value: 'Haveli Lakha' },
            { label: 'Hub', value: 'Hub' },
            { label: 'Hunza Nagar', value: 'Hunza Nagar' },
            { label: 'Hurnai', value: 'Hurnai' },
            { label: 'Hussain Bux Mari', value: 'Hussain Bux Mari' },
            { label: 'Hyderabad', value: 'Hyderabad' },
            { label: 'Ishkoman', value: 'Ishkoman' },
            { label: 'Islamabad', value: 'Islamabad' },
            { label: 'Islamkot', value: 'Islamkot' },
            { label: 'Jacobabad', value: 'Jacobabad' },
            { label: 'Jaffarabad', value: 'Jaffarabad' },
            { label: 'Jahaniyan', value: 'Jahaniyan' },
            { label: 'Jalalpur', value: 'Jalalpur' },
            { label: 'Jalalpur Jattan', value: 'Jalalpur Jattan' },
            { label: 'Jami Nawaz Ali', value: 'Jami Nawaz Ali' },
            { label: 'Jamrud', value: 'Jamrud' },
            { label: 'Jamshoro', value: 'Jamshoro' },
            { label: 'Kachhi', value: 'Kachhi' },
            { label: 'Kahan', value: 'Kahan' },
            { label: 'Kahror Pakka', value: 'Kahror Pakka' },
            { label: 'Kahuta', value: 'Kahuta' },
            { label: 'Kala Dhaka', value: 'Kala Dhaka' },
            { label: 'Kalabagh', value: 'Kalabagh' },
            { label: 'Kalat', value: 'Kalat' },
            { label: 'Kallar Kahar', value: 'Kallar Kahar' },
            { label: 'Kallar Sayyedan', value: 'Kallar Sayyedan' },
            { label: 'Kalur Kot', value: 'Kalur Kot' },
            { label: 'Kamalia', value: 'Kamalia' },
            { label: 'Kambar Ali Khan', value: 'Kambar Ali Khan' },
            { label: 'Kamoke', value: 'Kamoke' },
            { label: 'Kandhkot', value: 'Kandhkot' },
            { label: 'Kandia', value: 'Kandia' },
            { label: 'Kandaro', value: 'Kandaro' },
            { label: 'Kanraj', value: 'Kanraj' },
            { label: 'Karachi', value: 'Karachi' },
          ],
        },
        {
          label: 'Store Category',
          name: 'category',
          type: 'dropdown',
          show: ['Online', 'Retail'],
          options: [
            // { value: 'Online', label: 'Online' },
            { value: 'Retail', label: 'Retail' },
          ],
          required: true,
        },
        {
          label: 'Country Code',
          name: 'countryCode',
          type: 'text',
          show: ['Online', 'Retail'],
          required: true,
        },
        {
          label: 'State',
          name: 'state',
          type: 'text',
          show: ['Online', 'Retail'],
          required: true,
        },
        {
          label: 'POS Country Code',
          name: 'posCountryCode',
          type: 'text',
          show: ['Online', 'Retail'],
          required: true,
        },
      ],
    },
  ],
};
