export const punjabCities = [
  { label: 'Lahore', value: 'Lahore' },
  { label: 'Rawalpindi', value: 'Rawalpindi' },
  { label: 'Faisalabad', value: 'Faisalabad' },
  { label: 'Multan', value: 'Multan' },
  { label: 'Gujranwala', value: 'Gujranwala' },
  { label: 'Sialkot', value: 'Sialkot' },
  { label: 'Bahawalpur', value: 'Bahawalpur' },
  { label: 'Sargodha', value: 'Sargodha' },
  { label: 'Rahim Yar Khan', value: 'Rahim Yar Khan' },
  { label: 'Sheikhupura', value: 'Sheikhupura' },
  { label: 'Jhelum', value: 'Jhelum' },
  { label: 'Kasur', value: 'Kasur' },
  { label: 'Gujrat', value: 'Gujrat' },
  { label: 'Okara', value: 'Okara' },
  { label: 'Vehari', value: 'Vehari' },
  { label: 'Dera Ghazi Khan', value: 'Dera Ghazi Khan' },
  { label: 'Chiniot', value: 'Chiniot' },
  { label: 'Khushab', value: 'Khushab' },
  { value: 'Wah Cantt', label: 'Wah Cantt' },
  { label: 'Mandi Bahauddin', value: 'Mandi Bahauddin' },
  { label: 'Pakpattan', value: 'Pakpattan' },
  { label: 'Toba Tek Singh', value: 'Toba Tek Singh' },
  { label: 'Layyah', value: 'Layyah' },
  { label: 'Muzaffargarh', value: 'Muzaffargarh' },
  { label: 'Bhakkar', value: 'Bhakkar' },
  { label: 'Chakwal', value: 'Chakwal' },
  { label: 'Jhang', value: 'Jhang' },
  { label: 'Narowal', value: 'Narowal' },
  { label: 'Khanewal', value: 'Khanewal' },
  { label: 'Lodhran', value: 'Lodhran' },
];

export const sindhCities = [
  { label: 'Karachi', value: 'Karachi' },
  { label: 'Hyderabad', value: 'Hyderabad' },
  { label: 'Sukkur', value: 'Sukkur' },
  { label: 'Larkana', value: 'Larkana' },
  { label: 'Nawabshah', value: 'Nawabshah' },
  { label: 'Mirpur Khas', value: 'Mirpur Khas' },
  { label: 'Jacobabad', value: 'Jacobabad' },
  { label: 'Shikarpur', value: 'Shikarpur' },
  { label: 'Khairpur', value: 'Khairpur' },
  { label: 'Dadu', value: 'Dadu' },
  { label: 'Badin', value: 'Badin' },
  { label: 'Thatta', value: 'Thatta' },
  { label: 'Umerkot', value: 'Umerkot' },
  { label: 'Ghotki', value: 'Ghotki' },
  { label: 'Tando Allahyar', value: 'Tando Allahyar' },
  { label: 'Tando Muhammad Khan', value: 'Tando Muhammad Khan' },
  { label: 'Kashmore', value: 'Kashmore' },
  { label: 'Jamshoro', value: 'Jamshoro' },
  { label: 'Matiari', value: 'Matiari' },
  { label: 'Sanghar', value: 'Sanghar' },
];

export const peshawarCities = [
  { label: 'Peshawar', value: 'Peshawar' },
  { label: 'Abbottabad', value: 'Abbottabad' },
  { label: 'Mardan', value: 'Mardan' },
  { label: 'Swat', value: 'Swat' },
  { label: 'Kohat', value: 'Kohat' },
  { label: 'Dera Ismail Khan', value: 'Dera Ismail Khan' },
  { label: 'Bannu', value: 'Bannu' },
  { label: 'Mansehra', value: 'Mansehra' },
  { label: 'Haripur', value: 'Haripur' },
  { label: 'Chitral', value: 'Chitral' },
  { label: 'Nowshera', value: 'Nowshera' },
  { label: 'Swabi', value: 'Swabi' },
  { label: 'Hangu', value: 'Hangu' },
  { label: 'Dir', value: 'Dir' },
  { label: 'Karak', value: 'Karak' },
  { label: 'Tank', value: 'Tank' },
  { label: 'Charsadda', value: 'Charsadda' },
  { label: 'Shangla', value: 'Shangla' },
  { label: 'Buner', value: 'Buner' },
];

export const quettaCities = [
  { label: 'Quetta', value: 'Quetta' },
  { label: 'Gwadar', value: 'Gwadar' },
  { label: 'Turbat', value: 'Turbat' },
  { label: 'Khuzdar', value: 'Khuzdar' },
  { label: 'Sibi', value: 'Sibi' },
  { label: 'Zhob', value: 'Zhob' },
  { label: 'Chaman', value: 'Chaman' },
  { label: 'Panjgur', value: 'Panjgur' },
  { label: 'Loralai', value: 'Loralai' },
  { label: 'Nushki', value: 'Nushki' },
  { label: 'Kharan', value: 'Kharan' },
  { label: 'Lasbela', value: 'Lasbela' },
  { label: 'Kalat', value: 'Kalat' },
  { label: 'Pasni', value: 'Pasni' },
  { label: 'Awaran', value: 'Awaran' },
];

export const gilgitCities = [
  { label: 'Gilgit', value: 'Gilgit' },
  { label: 'Skardu', value: 'Skardu' },
  { label: 'Hunza', value: 'Hunza' },
  { label: 'Chilas', value: 'Chilas' },
  { label: 'Ghizer', value: 'Ghizer' },
  { label: 'Khaplu', value: 'Khaplu' },
  { label: 'Astore', value: 'Astore' },
  { label: 'Shigar', value: 'Shigar' },
  { label: 'Gupis', value: 'Gupis' },
  { label: 'Yasin', value: 'Yasin' },
];

export const federalCities = [{ label: 'Islamabad', value: 'Islamabad' }];

export const azadKashmirCities = [
  { label: 'Muzaffarabad', value: 'Muzaffarabad' },
  { label: 'Mirpur', value: 'Mirpur' },
  { label: 'Kotli', value: 'Kotli' },
  { label: 'Rawalakot', value: 'Rawalakot' },
  { label: 'Bagh', value: 'Bagh' },
  { label: 'Bhimber', value: 'Bhimber' },
  { label: 'Haveli', value: 'Haveli' },
  { label: 'Sudhanoti', value: 'Sudhanoti' },
  { label: 'Pallandri', value: 'Pallandri' },
  { label: 'Athmuqam', value: 'Athmuqam' },
];

export const generalCities = [
  { value: 'Islamabad', label: 'Islamabad' },
  { value: 'Karachi', label: 'Karachi' },
  { value: 'Lahore', label: 'Lahore' },
  { value: 'Rawalpindi', label: 'Rawalpindi' },
  { value: 'Peshawar', label: 'Peshawar' },
  { value: 'Quetta', label: 'Quetta' },
  { value: 'Faisalabad', label: 'Faisalabad' },
  { value: 'Multan', label: 'Multan' },
  { value: 'Hyderabad', label: 'Hyderabad' },
  { value: 'Sialkot', label: 'Sialkot' },
  { value: 'Bahawalpur', label: 'Bahawalpur' },
  { value: 'Gujranwala', label: 'Gujranwala' },
  { value: 'Sargodha', label: 'Sargodha' },
  { value: 'Sheikhupura', label: 'Sheikhupura' },
  { value: 'Mardan', label: 'Mardan' },
  { value: 'Kasur', label: 'Kasur' },
  { value: 'Rahim Yar Khan', label: 'Rahim Yar Khan' },
  { value: 'Jhelum', label: 'Jhelum' },
  { value: 'Abbottabad', label: 'Abbottabad' },
  { value: 'Okara', label: 'Okara' },
  { value: 'Wah Cantt', label: 'Wah Cantt' },
  { value: 'Mingora', label: 'Mingora' },
  { value: 'Mirpur', label: 'Mirpur' },
  { value: 'Nowshera', label: 'Nowshera' },
  { value: 'Swabi', label: 'Swabi' },
  { value: 'Muzaffarabad', label: 'Muzaffarabad' },
  { value: 'Gujrat', label: 'Gujrat' },
  { value: 'Dera Ghazi Khan', label: 'Dera Ghazi Khan' },
  { value: 'Chiniot', label: 'Chiniot' },
  { value: 'Kamoke', label: 'Kamoke' },
  { value: 'Toba Tek Singh', label: 'Toba Tek Singh' },
  { value: 'Khuzdar', label: 'Khuzdar' },
  { value: 'Mansehra', label: 'Mansehra' },
  { value: 'Kohat', label: 'Kohat' },
  { value: 'Pakpattan', label: 'Pakpattan' },
  { value: 'Dera Ismail Khan', label: 'Dera Ismail Khan' },
  { value: 'Sahiwal', label: 'Sahiwal' },
  { value: 'Chakwal', label: 'Chakwal' },
  { value: 'Vehari', label: 'Vehari' },
  { value: 'Ghotki', label: 'Ghotki' },
  { value: 'Larkana', label: 'Larkana' },
  { value: 'Jacobabad', label: 'Jacobabad' },
  { value: 'Shikarpur', label: 'Shikarpur' },
  { value: 'Khairpur', label: 'Khairpur' },
  { value: 'Bannu', label: 'Bannu' },
  { value: 'Hafizabad', label: 'Hafizabad' },
  { value: 'Sukkur', label: 'Sukkur' },
  { value: 'Jamshoro', label: 'Jamshoro' },
  { value: 'Narowal', label: 'Narowal' },
];
