export interface BankAccountDTO {
  bankPrefix: string;
  bankName: string;
  // You can add more properties if needed
}

export const bankAccountsDTO: BankAccountDTO[] = [
  { bankPrefix: 'MOD', bankName: 'Mod' },
  { bankPrefix: 'ABL', bankName: 'ABL' },
  { bankPrefix: 'ACBL', bankName: 'ACBL' },
  { bankPrefix: 'APNA', bankName: 'APNA' },
  { bankPrefix: 'BAB', bankName: 'ALB' },
  { bankPrefix: 'BAF', bankName: 'BAF' },
  { bankPrefix: 'BAH', bankName: 'BAH' },
  { bankPrefix: 'BBL', bankName: 'BBL' },
  { bankPrefix: 'BIPL', bankName: 'BIP' },
  { bankPrefix: 'BOP', bankName: 'BOP' },
  { bankPrefix: 'CITI', bankName: 'CITI' },
  { bankPrefix: 'DIB', bankName: 'DIB' },
  { bankPrefix: 'FBL', bankName: 'FBL' },
  { bankPrefix: 'HBL', bankName: 'HBL' },
  { bankPrefix: 'HMB', bankName: 'HMB' },
  { bankPrefix: 'JSB', bankName: 'JSB' },
  { bankPrefix: 'KASB', bankName: 'KASB' },
  { bankPrefix: 'MCB', bankName: 'MCB' },
  { bankPrefix: 'MEZ', bankName: 'MEZ' },
  { bankPrefix: 'NIB', bankName: 'NIB' },
  { bankPrefix: 'SAMBA', bankName: 'SAMBA' },
  { bankPrefix: 'SBL', bankName: 'SBL' },
  { bankPrefix: 'SCB', bankName: 'SCB' },
  { bankPrefix: 'SILK', bankName: 'SILK' },
  { bankPrefix: 'SINDHBANK', bankName: 'SINDHBANK' },
  { bankPrefix: 'SUM', bankName: 'SUM' },
  { bankPrefix: 'UBANK', bankName: 'UBANK' },
  { bankPrefix: 'UBL', bankName: 'UBL' },
  { bankPrefix: 'WASEELA', bankName: 'JC' },
  { bankPrefix: 'NRSP', bankName: 'NRSP' },
  { bankPrefix: 'FINCA', bankName: 'SimSim' },
  { bankPrefix: 'TMFL', bankName: 'TMFL' },
  { bankPrefix: 'BOK', bankName: 'BOK' },
  { bankPrefix: 'TameerBank', bankName: 'TelenorBank' },
  { bankPrefix: 'FWB', bankName: 'FWB' },
  { bankPrefix: 'NBP', bankName: 'NBP' },
  { bankPrefix: 'MIB', bankName: 'MIB' },
  { bankPrefix: 'FMB', bankName: 'FMB' },
  { bankPrefix: 'ICBC', bankName: 'ICBC' },
  { bankPrefix: 'MCB', bankName: 'MCB' },
  { bankPrefix: 'Finja', bankName: 'Finja' },
  { bankPrefix: 'nayapay', bankName: 'NP' },
  { bankPrefix: 'ZTBL', bankName: 'ZTBL' },
  { bankPrefix: 'KMBL', bankName: 'KMBL' },
  { bankPrefix: 'Paymax', bankName: 'PMAX' },
  { bankPrefix: 'Sadapay', bankName: 'sadapay' },
];
