// Do NOt Remove Commented Fields

export const storeFields = [
  {
    label: 'Store Type *',
    name: 'storeType',
    type: 'checkbox',
    options: [
      // { value: 'Online', label: 'Online' },
      { value: 'Retail', label: 'Retail' },
    ],
  },
  // {
  //   label: 'Web Store Name *',
  //   name: 'webstoreName',
  //   type: 'text',
  //   show: ['Online'],
  // },
  {
    label: 'Store Name *',
    name: 'storeName',
    type: 'text',
    show: ['Online', 'Retail'],
  },
  // {
  //   label: 'Website URL *',
  //   name: 'webstoreURL',
  //   type: 'text',
  //   show: ['Online'],
  // },

  {
    label: 'Street Address *',
    name: 'streetAddress',
    type: 'text',
    show: ['Online', 'Retail'],
  },
  {
    label: 'City *',
    name: 'city',
    type: 'dropdown',
    show: ['Online', 'Retail'],
    options: [
      { label: 'Abbaspur', value: 'Abbaspur' },
      { label: 'Abbottabad', value: 'Abbottabad' },
      { label: 'Adezai', value: 'Adezai' },
      { label: 'Ahmadpur East', value: 'Ahmadpur East' },
      { label: 'Ahmed Nager Chatha', value: 'Ahmed Nager Chatha' },
      { label: 'Ahmedpur Sial', value: 'Ahmedpur Sial' },
      { label: 'Akora Khattak', value: 'Akora Khattak' },
      { label: 'Alai', value: 'Alai' },
      { label: 'Ali Abad', value: 'Ali Abad' },
      { label: 'Ali Khan Abad', value: 'Ali Khan Abad' },
      { label: 'Alipur', value: 'Alipur' },
      { label: 'Alizai', value: 'Alizai' },
      { label: 'Alpuri', value: 'Alpuri' },
      { label: 'Arifwala', value: 'Arifwala' },
      { label: 'Astore', value: 'Astore' },
      { label: 'Athmuqam', value: 'Athmuqam' },
      { label: 'Attock', value: 'Attock' },
      { label: 'Awaran', value: 'Awaran' },
      { label: 'Ayubia', value: 'Ayubia' },
      { label: 'Baba Kot', value: 'Baba Kot' },
      { label: 'Badin', value: 'Badin' },
      { label: 'Bagh', value: 'Bagh' },
      { label: 'Bahawalnagar', value: 'Bahawalnagar' },
      { label: 'Bahawalpur', value: 'Bahawalpur' },
      { label: 'Bajour Agency', value: 'Bajour Agency' },
      { label: 'Bakrani', value: 'Bakrani' },
      { label: 'Bala Kot', value: 'Bala Kot' },
      { label: 'Balambat Lal Qilla', value: 'Balambat Lal Qilla' },
      { label: 'Baloch', value: 'Baloch' },
      { label: 'Banda Daud Shah', value: 'Banda Daud Shah' },
      { label: 'Bannu', value: 'Bannu' },
      { label: 'Bara', value: 'Bara' },
      { label: 'Barawal', value: 'Barawal' },
      { label: 'Barkhan', value: 'Barkhan' },
      { label: 'Barnala', value: 'Barnala' },
      { label: 'Batkhela', value: 'Batkhela' },
      { label: 'Battagram', value: 'Battagram' },
      { label: 'Bela', value: 'Bela' },
      { label: 'Besima', value: 'Besima' },
      { label: 'Bhag', value: 'Bhag' },
      { label: 'Bhakkar', value: 'Bhakkar' },
      { label: 'Bhalwal', value: 'Bhalwal' },
      { label: 'Bhawana', value: 'Bhawana' },
      { label: 'Bhera', value: 'Bhera' },
      { label: 'Bhimber', value: 'Bhimber' },
      { label: 'Bhiria Road', value: 'Bhiria Road' },
      { label: 'Bhirkan', value: 'Bhirkan' },
      { label: 'Birote', value: 'Birote' },
      { label: 'Bisham', value: 'Bisham' },
      { label: 'Bolan(Dhadar)', value: 'Bolan(Dhadar)' },
      { label: 'Bulri Shah Karim', value: 'Bulri Shah Karim' },
      { label: 'Bunair', value: 'Bunair' },
      { label: 'Burewala', value: 'Burewala' },
      { label: 'Chachro', value: 'Chachro' },
      { label: 'Chaghi', value: 'Chaghi' },
      { label: 'Chak', value: 'Chak' },
      { label: 'Chak Jhumra', value: 'Chak Jhumra' },
      { label: 'Chakdara', value: 'Chakdara' },
      { label: 'Chakesar', value: 'Chakesar' },
      { label: 'Chakwal', value: 'Chakwal' },
      { label: 'Chaman', value: 'Chaman' },
      { label: 'Chamber', value: 'Chamber' },
      { label: 'Charoai', value: 'Charoai' },
      { label: 'Charsadda', value: 'Charsadda' },
      { label: 'Chattar', value: 'Chattar' },
      { label: 'Chaubara', value: 'Chaubara' },
      { label: 'Chitral', value: 'Chitral' },
      { label: 'Chowk Azam', value: 'Chowk Azam' },
      { label: 'Cherat', value: 'Cherat' },
      { label: 'Chichawatni', value: 'Chichawatni' },
      { label: 'Chikar', value: 'Chikar' },
      { label: 'Chilas', value: 'Chilas' },
      { label: 'Chillianwala', value: 'Chillianwala' },
      { label: 'Chiniot', value: 'Chiniot' },
      { label: 'Chistian', value: 'Chistian' },
      { label: 'Chowk Munda', value: 'Chowk Munda' },
      { label: 'Chowk Sarwar Shaheed', value: 'Chowk Sarwar Shaheed' },
      { label: 'Choa Saidan Shah', value: 'Choa Saidan Shah' },
      { label: 'Chunian', value: 'Chunian' },
      { label: 'Dadu', value: 'Dadu' },
      { label: 'Daggar', value: 'Daggar' },
      { label: 'Daharki', value: 'Daharki' },
      { label: 'Dajkot', value: 'Dajkot' },
      { label: 'Dalbadin', value: 'Dalbadin' },
      { label: 'Daraban', value: 'Daraban' },
      { label: 'Darail', value: 'Darail' },

      { label: 'Dargai', value: 'Dargai' },
      { label: 'Darra Adam Khel', value: 'Darra Adam Khel' },
      { label: 'Darya Khan', value: 'Darya Khan' },
      { label: 'Dasht ', value: 'Dasht' },
      { label: 'Daska', value: 'Daska' },
      { label: 'Dassu', value: 'Dassu' },
      { label: 'Daur', value: 'Daur' },
      { label: 'Davispur', value: 'Davispur' },
      { label: 'Dera Allah Yar', value: 'Dera Allah Yar' },
      { label: 'Dera Bugti', value: 'Dera Bugti' },
      { label: 'Dera Ghazi Khan', value: 'Dera Ghazi Khan' },
      { label: 'Dera Ismail Khan', value: 'Dera Ismail Khan' },
      { label: 'Dera Murad Jamali', value: 'Dera Murad Jamali' },
      { label: 'Dhaular', value: 'Dhaular' },
      { label: 'Dhir Kot', value: 'Dhir Kot' },
      { label: 'Diamir', value: 'Diamir' },
      { label: 'Digri', value: 'Digri' },
      { label: 'Dina', value: 'Dina' },
      { label: 'Dipalpur', value: 'Dipalpur' },
      { label: 'Diplo', value: 'Diplo' },
      { label: 'Dir', value: 'Dir' },
      { label: 'Doaba', value: 'Doaba' },
      { label: 'Dokri', value: 'Dokri' },
      { label: 'Dolatpur', value: 'Dolatpur' },
      { label: 'Domel', value: 'Domel' },
      { label: 'Drosh', value: 'Drosh' },
      { label: 'Dudyal(AK)', value: 'Dudyal(AK)' },
      { label: 'Duki', value: 'Duki' },
      { label: 'Dunyapur', value: 'Dunyapur' },
      { label: 'Dureji', value: 'Dureji' },
      { label: 'Essa Khel', value: 'Essa Khel' },
      { label: 'Faisalabad', value: 'Faisalabad' },
      { label: 'Faiz Ganj', value: 'Faiz Ganj' },
      { label: 'Fateh Jang', value: 'Fateh Jang' },

      { label: 'Feroze Wala', value: 'Feroze Wala' },
      { label: 'Fort Abbas', value: 'Fort Abbas' },
      { label: 'Forward Kahuta', value: 'Forward Kahuta' },
      { label: 'Gaddani', value: 'Gaddani' },
      { label: 'Gambat', value: 'Gambat' },
      { label: 'Gandaka', value: 'Gandaka' },
      { label: 'Garhi Khairo', value: 'Garhi Khairo' },
      { label: 'Garhi Yasin', value: 'Garhi Yasin' },
      { label: 'Ghakar Mandi', value: 'Ghakar Mandi' },
      { label: 'Ghandawa', value: 'Ghandawa' },
      { label: 'Ghangchi', value: 'Ghangchi' },
      { label: 'Ghazi', value: 'Ghazi' },
      { label: 'Ghizer', value: 'Ghizer' },
      { label: 'Ghorabari', value: 'Ghorabari' },
      { label: 'Ghotki', value: 'Ghotki' },
      { label: 'Ghulam Khana Mehrabpur', value: 'Ghulam Khana Mehrabpur' },
      { label: 'Gilgit', value: 'Gilgit' },
      { label: 'Gishkore', value: 'Gishkore' },
      { label: 'Gojal', value: 'Gojal' },
      { label: 'Gojra', value: 'Gojra' },
      { label: 'Golarchi', value: 'Golarchi' },
      { label: 'Gowargo', value: 'Gowargo' },
      { label: 'Gujar Khan', value: 'Gujar Khan' },
      { label: 'Gujranwala', value: 'Gujranwala' },
      { label: 'Gujrat', value: 'Gujrat' },
      { label: 'Gulistan', value: 'Gulistan' },
      { label: 'Gultari', value: 'Gultari' },
      { label: 'Gupi', value: 'Gupi' },
      { label: 'Gwadar', value: 'Gwadar' },
      { label: 'Haala', value: 'Haala' },
      { label: 'Hafizabad', value: 'Hafizabad' },
      { label: 'Hajeera', value: 'Hajeera' },
      { label: 'Hangu', value: 'Hangu' },
      { label: 'Harappa', value: 'Harappa' },
      { label: 'Haripur', value: 'Haripur' },
      { label: 'Harnai', value: 'Harnai' },
      { label: 'Haroonabad', value: 'Haroonabad' },
      { label: 'Hasilpur', value: 'Hasilpur' },
      { label: 'Haveli Kahuta', value: 'Haveli Kahuta' },
      { label: 'Haveli', value: 'Haveli' },
      { label: 'Hassan Abdal Hazro', value: 'Hassan Abdal Hazro' },
      { label: 'Hattian Bala', value: 'Hattian Bala' },
      { label: 'Hasil', value: 'Hasil' },
      { label: 'Jamshoro', value: 'Jamshoro' },
      { label: 'Jand', value: 'Jand' },
      { label: 'Jaranwala', value: 'Jaranwala' },
      { label: 'Jati', value: 'Jati' },
      { label: 'Jatoi', value: 'Jatoi' },
      { label: 'Jauharabad', value: 'Jauharabad' },
      { label: 'Jhal Magsi', value: 'Jhal Magsi' },
      { label: 'Jhaljao', value: 'Jhaljao' },
      { label: 'Jhando Mar', value: 'Jhando Mar' },
      { label: 'Jhang', value: 'Jhang' },
      { label: 'Jhelum', value: 'Jhelum' },
      { label: 'Jhel Pat', value: 'Jhel Pat' },
      { label: 'Jhuddo', value: 'Jhuddo' },
      { label: 'Jiwani', value: 'Jiwani' },
      { label: 'Johi', value: 'Johi' },
      { label: 'Jangshahi', value: 'Jangshahi' },
      { label: 'Kabir Wala', value: 'Kabir Wala' },
      { label: 'Kachhi', value: 'Kachhi' },
      { label: 'Haveli Lakha', value: 'Haveli Lakha' },
      { label: 'Hub', value: 'Hub' },
      { label: 'Hunza Nagar', value: 'Hunza Nagar' },
      { label: 'Hurramzai', value: 'Hurramzai' },
      { label: 'Hussain Bux Mari', value: 'Hussain Bux Mari' },
      { label: 'Hyderabad', value: 'Hyderabad' },
      { label: 'Ishkoman', value: 'Ishkoman' },
      { label: 'Islamabad', value: 'Islamabad' },
      { label: 'Islamkot', value: 'Islamkot' },
      { label: 'Jacobabad', value: 'Jacobabad' },
      { label: 'Jaffarabad', value: 'Jaffarabad' },
      { label: 'Jahanian', value: 'Jahanian' },
      { label: 'Jalalpur', value: 'Jalalpur' },
      { label: 'Jalalpur Jattan', value: 'Jalalpur Jattan' },
      { label: 'Jam Nawaz Ali', value: 'Jam Nawaz Ali' },
      { label: 'Jampur', value: 'Jampur' },
      { label: 'Jamrud', value: 'Jamrud' },
      { label: 'Jamshoro', value: 'Jamshoro' },
      { label: 'Kachhi', value: 'Kachhi' },
      { label: 'Kahan', value: 'Kahan' },
      { label: 'Kahror Pakka', value: 'Kahror Pakka' },
      { label: 'Kahuta', value: 'Kahuta' },
      { label: 'Kala Dhaka', value: 'Kala Dhaka' },
      { label: 'Kalabagh', value: 'Kalabagh' },
      { label: 'Kalat', value: 'Kalat' },
      { label: 'Kallar Kahar', value: 'Kallar Kahar' },
      { label: 'Kallar Sayyedan', value: 'Kallar Sayyedan' },
      { label: 'Kalur Kot', value: 'Kalur Kot' },
      { label: 'Kamalia', value: 'Kamalia' },
      { label: 'Kambar Ali Khan', value: 'Kambar Ali Khan' },
      { label: 'Kamoke', value: 'Kamoke' },
      { label: 'Kandhkot', value: 'Kandhkot' },
      { label: 'Kandia', value: 'Kandia' },
      { label: 'Kandiaro', value: 'Kandiaro' },
      { label: 'Kanraj', value: 'Kanraj' },
      { label: 'Karachi', value: 'Karachi' },
    ],
  },
  {
    label: 'Store Category *',
    name: 'category',
    type: 'dropdown',
    show: ['Online', 'Retail'],
    // options: storeCategoryList,
  },
  {
    label: 'Country Code *',
    name: 'countryCode',
    type: 'text',
    show: ['Online', 'Retail'],
  },
  {
    label: 'State *',
    name: 'state',
    type: 'text',
    show: ['Online', 'Retail'],
  },
  {
    label: 'POS Country Code *',
    name: 'posCountryCode',
    type: 'text',
    show: ['Online', 'Retail'],
  },
];
